### ISSUE TITLE
Improving TLS session to elasticsearch sink in dataflow

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/public-issues#1]
# JIRA Issue

https://issues.apache.org/jira/browse/BEAM-7519

# Tasks

- [x]  Set elasticsearch in minikube
- [x]  Sample direct runner using elasticsearch sink without TLS  with TLS session
- [x] Post comment to JIRA

# Reference

### Abount news about eck on kubernetes
https://www.elastic.co/blog/alpha-helm-charts-for-elasticsearch-kibana-and-cncf-membership

### About kubernetes objects
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#kubernetes-objects

# Things to learn

* How to write deployments
* How to setup elasticsearch
* Java

**Comment by yuwtennis** [comment]
### Certificate signe request

```
openssl x509 -req -in elasticsearch/http-localhost.csr -CAkey ca/ca.key -CA ca/ca.crt -CAcreateserial -out elasticsearch/http-localhost.crt
```
